#!/usr/bin/env node

import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = join(packageRoot, "dist");
const stagingDirectory = join(packageRoot, ".pi-x-footer-dist-staging");
const generatedBanner = [
	"// @generated by scripts/build-runtime.mjs; do not edit.",
	"// @ts-nocheck -- the generated entry uses a .ts extension for Pi's Jiti loader.",
].join("\n");

await rm(stagingDirectory, { force: true, recursive: true });
await mkdir(stagingDirectory, { recursive: true });

try {
	await build({
		absWorkingDir: packageRoot,
		banner: { js: generatedBanner },
		bundle: true,
		entryPoints: ["src/index.ts"],
		format: "esm",
		legalComments: "none",
		outfile: join(stagingDirectory, "index.js"),
		packages: "external",
		platform: "node",
		sourcemap: true,
		target: "es2022",
		write: true,
	});

	const javascriptPath = join(stagingDirectory, "index.js");
	const typescriptPath = join(stagingDirectory, "index.ts");
	const javascriptMapPath = join(stagingDirectory, "index.js.map");
	const typescriptMapPath = join(stagingDirectory, "index.ts.map");
	const source = await readFile(javascriptPath, "utf8");
	const rewritten = source.replace(
		"sourceMappingURL=index.js.map",
		"sourceMappingURL=index.ts.map",
	);
	await writeFile(javascriptPath, rewritten, "utf8");
	await rename(javascriptMapPath, typescriptMapPath);
	await rename(javascriptPath, typescriptPath);

	await rm(outputDirectory, { force: true, recursive: true });
	await rename(stagingDirectory, outputDirectory);
} catch (error) {
	await rm(stagingDirectory, { force: true, recursive: true });
	throw error;
}
